AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends log data from S3 to New Relic Logging.
Parameters:
  NRLicenseKey:
    Type: String
    Description: Your NewRelic license key. You may omit it when deploying the function.
    Default: "YOUR_LICENSE_KEY"

Metadata:
  AWS::ServerlessRepo::Application:
    Name: S3-newrelic-Log-Ingestion-Lambda
    Description: New Relic S3 Log Ingestion Lambda
    Author: New Relic
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['newrelic', 'logs', 's3']
    HomePageUrl: https://github.com/newrelic/aws_s3_log_ingestion_lambda
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/newrelic/aws_s3_log_ingestion_lambda

Resources:
  NewRelicLogIngestionFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      CodeUri: src/
      Handler: handler.lambda_handler
      FunctionName: NewRelic-s3-log-ingestion
      Timeout: 30
      Environment:
        Variables: 
          LICENSE_KEY: !Ref NRLicenseKey
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceLogBucket
            Events:
              - 's3:ObjectCreated:*'

  SourceLogBucket:
    Type: 'AWS::S3::Bucket'